run:
  deadline: 5m
linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - goimports
    - gocritic
linters-settings:
  lll:
    line-length: 420
  gocyclo:
    min-complexity: 40

issues:
  exclude-rules:
    - path: "exported.go"
      linters:
        - dupl
